global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'inventory-app'
    metrics_path: '/inventory/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'inventory-management-system'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']